# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoottikala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosplayer',
            name='social_media_links',
            field=models.TextField(blank=True, help_text='Jos sinulla on cosplay-profiili esim. Facebookissa tai Twitterissä, syötä niiden osoitteet tähän, yksi per rivi (pelkkä osoite, https://…).', verbose_name='Sosiaalisen median linkit'),
        ),
    ]
