# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-10 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoottikala', '0002_cosplayer_social_media_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cosplayer',
            options={'ordering': ('event', 'created_at')},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='cosplayer',
            name='source_type',
            field=models.CharField(choices=[('anime', 'Anime'), ('other_anim', 'Muu animaatiosarja'), ('manga', 'Manga'), ('other_comic', 'Muu sarjakuva'), ('movie', 'Elokuva'), ('series', 'TV-sarja'), ('game', 'Videopeli'), ('original', 'Originaalihahmo'), ('other', 'Muu')], max_length=11, verbose_name='Lähdeteoksen tyyppi'),
        ),
    ]
