# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoottikala', '0003_auto_20170210_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('abbreviation', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'Päivä',
                'verbose_name_plural': 'Päivät',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='photographer',
            options={'ordering': ('event', 'created_at')},
        ),
        migrations.AddField(
            model_name='cosplayer',
            name='days',
            field=models.ManyToManyField(blank=True, help_text='Ruksaa tästä, mille tapahtumapäiville etsit shoottia tässä asussa.', related_name='_cosplayer_days_+', to='shoottikala.Day', verbose_name='Tapahtumapäivät'),
        ),
        migrations.AddField(
            model_name='photographer',
            name='days',
            field=models.ManyToManyField(blank=True, help_text='Ruksaa tästä, minä tapahtumapäivinä olet käytettävissä photoshooteille.', related_name='_photographer_days_+', to='shoottikala.Day', verbose_name='Tapahtumapäivät'),
        ),
    ]
