# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoottikala', '0005_photographer_is_official'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiated_by', models.CharField(choices=[('c', 'Cosplayer'), ('p', 'Photographer')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cosplayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoottikala.Cosplayer')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoottikala.Photographer')),
            ],
        ),
    ]
