# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-30 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoshoots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='homepage_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
